Include null check for setting minion tag.
apache/incubator-pinot pull request #7033
Opened 2021-06-08 19:52 UTC by amrishlal

## Description
Null check to ensure that a default tag will be added for Pinot Minion instance even when `instanceTags` are null. Broker and Server already carry out similar null check.
## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)
## Release Notes

## Documentation

2021-06-08 19:54 UTC, amrishlal commented
@jackjlli Please review.

2021-06-08 20:20 UTC, jackjlli approved these changes
LGMT. Thanks!

2021-06-08 23:48 UTC, jackjlli requested changes

2021-06-08 23:48 UTC, jackjlli commented on pinot-minion/src/main/java/org/apache/pinot/minion/MinionStarter.java
> +    List<String> instanceTags = instanceConfig.getTags();
The returned instanceConfig could be null if record is null. @amrishlal Please add the check `instanceConfig == null ` as well.

```
  public static <T extends HelixProperty> T convertToTypedInstance(Class<T> clazz, ZNRecord record) {
    if (record == null) {
      return null;
    }

    try {
      Constructor<T> constructor = clazz.getConstructor(ZNRecord.class);
      return constructor.newInstance(record);
    } catch (Exception e) {
      LOG.error("Exception convert znrecord: " + record + " to class: " + clazz, e);
    }

    return null;
  }
```

2021-06-08 23:55 UTC, jackjlli commented
> `InstanceConfig.getTags()` should never return `null`. Are you using a different Helix version?
> Here's the Helix code:
> 
> ```
>   public List<String> getTags() {
>     List<String> tags = getRecord().getListField(InstanceConfigProperty.TAG_LIST.toString());
>     if (tags == null) {
>       tags = new ArrayList<String>(0);
>     }
>     return tags;
>   }
> ```

Thanks for pointing out! The purpose of this PR is to address an issue when the helix tag for minion host is missing, and we suspect that it's due to an NPE from this part of code. @amrishlal we can remove the null check for the returned reference of getTags, while a null check is needed for instanceConfig. Please include that into this PR.

2021-06-09 06:22 UTC, amrishlal commented
> we can remove the null check for the returned reference of getTags, while a null check is needed for instanceConfig. Please include that into this PR.

Fixed.

2021-06-09 21:23 UTC, jackjlli approved these changes

2021-06-09 21:29 UTC, merged

2021-06-10 17:49 UTC, Jackie-Jiang reviewed
When we are not able to get the instance config (unexpected), we should consider throwing an exception instead of blindly setting the tag because we don't know the existing tag

2021-06-10 18:15 UTC, jackjlli commented
There is only one possible helix tag in minion, which is `minion_untagged`. If it's set to another tags or no tag at all, the minion host won't pick up any task, so basically it will be idle.

2021-06-10 21:33 UTC, Jackie-Jiang commented
@jackjlli I understand why we should add the tag. My question is on when the minion fails to read the instance config (usually due to ZK or connection issue), should we abort or just blindly add the tag. With the current Helix implementation, blindly adding the tag is okay because internally it will dedup the tag, but it relies on the Helix implementation and could cause unexpected behavior if using a different Helix version